# Use the official MySQL image as the base image
FROM mysql:8

# Set environment variables
ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=sheba
ENV MYSQL_USER=root
ENV MYSQL_PASSWORD=

# Copy the SQL script to initialize the database
COPY init.sql /docker-entrypoint-initdb.d/